### ISSUE TITLE
Add verification k8s job to verify if app in created pod is up, running and reachable

### ISSUE THREAD

**Issue by JanMate** [JanMate/happy_bank_infra#35]

**Comment by JanMate** [comment]
@Oleksandr6676, I pushed docker image with health check REST api endpoint to docker hub, so you can switch from busybox to this image: https://hub.docker.com/r/jmatejka/happy-bank-core/tags

I'll create a new task for it.

**Comment by Oleksandr6676** [comment]
Hi @JanMate! Could you please help me with this one? Any advice would be appreciated!
I've faced an issue while trying to send curl request to my core-app-svc, I always get "Failed to connect to core-app-svc port 80: Connection refused" error, however it works fine when I'm sending request to the default kubernetes service (curl -v http://kubernetes:443 - I get status code 400 in this case, so the curl command and k8s job itself works properly). 
Now I'm trying to figure out what can cause this error, either I have some issues with service or pod setup or "server" is not running inside the container. Maybe I need to add some extra commands to make our app running and processing requests from outside the container? 
Thank you!

**Comment by JanMate** [comment]
> Hi @JanMate! Could you please help me with this one? Any advice would be appreciated! I've faced an issue while trying to send curl request to my core-app-svc, I always get "Failed to connect to core-app-svc port 80: Connection refused" error, however it works fine when I'm sending request to the default kubernetes service (curl -v http://kubernetes:443 - I get status code 400 in this case, so the curl command and k8s job itself works properly). Now I'm trying to figure out what can cause this error, either I have some issues with service or pod setup or "server" is not running inside the container. Maybe I need to add some extra commands to make our app running and processing requests from outside the container? Thank you!

Check pod's logs, maybe you will see what the issue is.
