### ISSUE TITLE
Study how the code review should happen

### ISSUE THREAD

**Issue by JanMate** [JanMate/happy_bank_infra#38]
Study following links:
 - https://mtlynch.io/code-review-love/
 - https://mtlynch.io/human-code-reviews-1/

**Comment by Oleksandr6676** [comment]
Hi @JanMate , I've studied these links so I marked this issue as closed.

**Comment by JanMate** [comment]
Sorry @Oleksandr6676, I forget to this link https://reflectoring.io/meaningful-commit-messages/. My apology. 

Opening this issue once again.
