### ISSUE TITLE
Create k8s secret 'core-secret' for security

### ISSUE THREAD

**Issue by JanMate** [JanMate/happy_bank_infra#45]
The secret will contain only one key - token.
The values of token will be automatically generated via sha1 cypher from current timestamp.

**Comment by Oleksandr6676** [comment]
Hi Jan! Could you please advise how can I pass the token to the yaml file? Is it possible to generate token inside the yaml file or do I need to create separate shell script with token variable and then pass it to core-secret file?

**Comment by JanMate** [comment]
> Hi Jan! Could you please advise how can I pass the token to yaml file? Is it possible to generate token inside the yaml file or do I need to create separate shell script with token variable and then pass it to core-secret file?

Great question and catch! As far as I know, the yaml manifest is a static file, so probably there is no way to specify a code to processing. Thus, you should add the token generation to 'k8s_deploy.sh' in #36. However there should be at least placeholder for value of the token in the yaml manifest.

Study: https://learnk8s.io/templating-yaml-with-code
