### ISSUE TITLE
Create k8s configmap 'redis-configmap' with redis configuration

### ISSUE THREAD

**Issue by JanMate** [JanMate/happy_bank_infra#53]
The configmap will contain configuration to connect from other microservices.

**Comment by Oleksandr6676** [comment]
Hi @JanMate . I am absolutely new to redis. Should I watch some redis tutorials as well? 
Also I found an example of redis configuration file here https://raw.githubusercontent.com/redis/redis/6.2/redis.conf and copied all contents to redis-config.yaml on my local branch. This config file is quite huge, do we need to make some changes inside of it? 
I will also go through this file and try to understand what is going on there.
