### ISSUE TITLE
Implement clone_update_repo.sh script

### ISSUE THREAD

**Issue by JanMate** [JanMate/happy_bank_infra#9]
Replace "TODOs" in the clone_upgrade_repo.sh script with your implementation by the instruction above it.

If you have no clue by any of tasks, do not hesitate to open discussion, either in this issue or in a pull request that you would have opened.

**Comment by Oleksandr6676** [comment]
Hi Jan! Could you pls help with this task: 
"Update README in cloned repo - copy there the differences of the file in this repo
 Commit message and Workflow sub-sections (Hint: Try to use "head" or "tail" command + pipe "|" to redirect output)" 
I've already copied the repositorty and created new branch. But I didn't quite clear understand what differences I have to copy.

**Comment by JanMate** [comment]
Of course, I can. No problem! 

README.md file in the cloned repo contains these 2 lines:
```
# happy_bank_core
This repo contains the simple example of bank core backend app.
```
And README.md file in this repo contains: 
```
# happy_bank_infra
This repo contains the simple example of bank infrastructure.

## Commit message format:

severity: Header sentence
Body paragraph.
Mentioning issue ID

**severity**: minor, major, critical<br>
**mentioning** must contains keywords: closes, fixes, resolves

...
```

So, the task is about to select the content of the file from this repo except first 3 lines and paste it into the README.md file in the cloned repo. `tail` bash tool could be quite useful in this case.

Steps:
1.  print a file content
2. select content from 4th line
3. redirect output into other file

These steps must be joined by pipe "|" to redirect output to input another command/tool.

Is it more clear? If not, describe your imagination and let's take it together.

**Comment by JanMate** [comment]
I hope you understood why it's better to solve the git credentials in higher layer than in the script itself. As I mentioned, you should think as a team member and count on different environments. These environments have always own purpose to do.

Typically, there are environments like:
- development
- testing
- staging
- production
